# manual steps to install dotnet6.0
# sudo apt update
# sudo apt install dotnet-sdk-6.0 -y or sudo apt-get install -y dotnet-sdk-6.0
# dotnet --version
# dotnet --list-sdks

---
- name: installation of specified dotnet version on ubuntu 22.04
  hosts: all
  become: yes
  vars:
    version: 6.0
  tasks:
    - name: installing dotnet
      ansible.builtin.apt:
        name: dotnet-sdk-{{version}}
        update_cache: yes
        state: present


# manual steps steps to install dotnet7.0
# sudo apt update
# wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
# sudo dpkg -i packages-microsoft-prod.deb
# sudo apt update
# sudo apt install dotnet-sdk-7.0 -y or sudo apt-get install -y dotnet-sdk-7.0
# dotnet --version
# dotnet --list-sdks

---
- name: installation of specified dotnet version on ubuntu 22.04
  hosts: all
  become: yes
  vars:
    version: 7.0
  tasks:
    - name: adding microsoft package
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        dest: /home/acn
    - name: Install debian package
      ansible.builtin.apt:
        deb: /home/acn/packages-microsoft-prod.deb
    - name: installing dotnet
      ansible.builtin.apt:
        name: dotnet-sdk-{{version}}
        update_cache: yes
        state: present
