# Manual: 
# sudo apt update
# sudo apt install apache2
# sudo apt install php libapache2-mod-php php-mysql
# Create a file info.php in this path /var/www/html/(this path will create after installing apache2)
# sudo nano /var/www/html/info.php
# <?php phpinfo();?>
# sudo systemctl enable apache2
# sudo systemctl start apache2
# sudo systemctl status apache2

- name: installation of apache server and php on UBUNTU 
  hosts: all
  become: yes
  tasks:
    - name: install apache2
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present
    - name: install php
      ansible.builtin.apt:
        name: 
          - php
          - libapache2-mod-php
          - php-mysql
        state: latest
        update_cache: yes
    - name: copy the file
      ansible.builtin.copy:
        dest: /var/www/html/info.php
        content:
          - <?php phpinfo();?>
        remote_src: true
    - name: start the service
      ansible.builtin.systemd:
        name: apache2
        enabled: true
        state: started
