# Manual: 
# sudo apt update
# sudo apt install default-jdk
# sudo groupadd -r wildfly
# sudo useradd -r -g wildfly -d /opt/wildfly -s /sbin/nologin wildfly
# WILDFLY_VERSION=16.0.0.Final
# wget https://download.jboss.org/wildfly/$WILDFLY_VERSION/wildfly-$WILDFLY_VERSION.tar.gz -P /tmp
# sudo tar xf /tmp/wildfly-$WILDFLY_VERSION.tar.gz -C /opt/
# sudo ln -s /opt/wildfly-$WILDFLY_VERSION /opt/wildfly
# sudo chown -RH wildfly: /opt/wildfly
# sudo mkdir -p /etc/wildfly
# sudo cp /opt/wildfly/docs/contrib/scripts/systemd/wildfly.conf /etc/wildfly/
# sudo cp /opt/wildfly/docs/contrib/scripts/systemd/launch.sh /opt/wildfly/bin/
# sudo sh -c 'chmod +x /opt/wildfly/bin/*.sh'
# sudo cp /opt/wildfly/docs/contrib/scripts/systemd/wildfly.service /etc/systemd/system/
# sudo systemctl daemon-reload
# sudo systemctl start wildfly
# sudo systemctl status wildfly
# sudo systemctl enable wildfly

- name: installation of apache server and php on UBUNTU 
  hosts: all
  become: yes
  tasks:
    - name: install jdk
    ansible.builtin.apt:
      name: default-jdk
      update_cache: yes
      state: present
    - name: add groups
    ansible.builtin.group:
      name: wildfly
      state: present